### ISSUE TITLE
Pages and content

### ISSUE THREAD

**Issue by monoai** [monoai/luna-fansite#8]
This is the working to-do list for the pages and content so that the website could be considered ready to launch, this can be modified, added or lessen, feel free to make any suggestions or launch a new issue to ensure we could make this fansite properly. Our worst case scenario is just launching the map page as is and work on other parts of the site later on.

---
# To-do list
- [ ] Implement react router to handle multiple pages
- [ ] Home
- This is the main landing page, should contain a welcoming message, a brief description about Himemori Luna, and [undecided] a section to explore the site/popular/current projects
- [ ] Projects
- Categorizes the projects made for the website and by the Candy Kingdom Server. Ideally has old projects, and if other people are willing, other-luna related projects if they want so.
   - [ ] A way to categorize projects at the page
     - Current thought is either drop it all as buttons similar to the holoEN project site, or we devise a way to add tags to projects so that we could categorize them in the future (Server Projects, Website Projects, etc.)
   - [ ] It should be easy to link/make new project pages
   - [ ] Map project should be featured immediately
- [ ] About
- Contains information about this site, credits to the developers
- Note: is this a good idea, or should we just make a page dedicated to resources/links? After all I kinda want to link the button site with the fansite as well.
---
# Notes
- It would be nice to have links of himesama somewhere on the header at all times
- Where can we advertise the discord server, or any affiliated servers if they wish?
