### ISSUE TITLE
Map Project Development

### ISSUE THREAD

**Issue by monoai** [monoai/luna-fansite#9]
These are the remaining tasks for the map project in order for us to finally start receiving submissions and launch the site.

# To-do list
- [ ] Welcome section of the page, congratulating himesama on 1m subscribers, indicating what this project is and what we're hoping for
- [ ] Paginated list of cards besides the map
- [ ] #7 
- [ ] Mobile-friendly layout
  - [ ] Check that layout works for PC, Tablet, and Phones
- [ ] Making sure translations works on the project for the necessary UI texts
# Possibly optional
- [ ] Points on the map should also link back to the card
